name: Update Comic Data

on:
  schedule:
    - cron: '*/30 * * * *' # Menjalankan robot setiap 30 menit
  workflow_dispatch:      # Tombol manual tetap aktif

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run Scraper
        run: |
          cd asn
          python scraper.py

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add asn/data.json
          git commit -m "Auto Update Data 30 Menit" || exit 0
          git push
