name: Update PetoMic Data

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
    inputs:
      target_slug:
        description: 'Slug ManhuaPlus (contoh: virus-king)'
        required: false
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Penting untuk proses rebase

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - run: pip install requests beautifulsoup4 cloudinary

      - env:
          CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
          TARGET_SLUG: ${{ github.event.inputs.target_slug }}
        run: |
          mkdir -p asn/db
          cd asn
          python scraper.py

      - name: Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add asn/
          
          if [ -n "$(git status --porcelain)" ]; then
            # Mengatasi error rejected dengan rebase sebelum push
            git pull --rebase origin main
            git commit -m "PetoMic Update: Fixed Images & Push [$(date)]"
            git push origin main
          else
            echo "Tidak ada perubahan data untuk di-push."
          fi
